content:
  - name: posts
    label: Posts
    path: src/pages/posts
    type: collection
    view:
      fields: [ title, description ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: body, label: Body, type: rich-text }